apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  users.anonymous.enabled: 'false'
  dex.config: |
    # Setting staticClients allows Argo Workflows to use Argo CD's Dex installation for authentication
    staticClients:
      # This is the OIDC client ID in plaintext
      - id: 521f153a-87bc-448a-8c34-7ae491e49de6
        name: Argo Workflow
        redirectURIs:
          - https://argowf.brandt.widdershoven.nl/oauth2/callback
        secretEnv: ARGO_WORKFLOW_SSO_CLIENT_SECRET