apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-dex-server
spec:
  template:
    spec:
      containers:
        - name: dex
          env:
            - name: ARGO_WORKFLOW_SSO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: argo-workflow-sso
                  key: client-secret