apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
spec:
  destination:
    namespace: example
    server: https://kubernetes.default.svc
  project: example-project
  source:
    path: bookinfo-example/kustomize
    repoURL: https://github.com/digitalocean/kubernetes-sample-apps.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
