apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: example-project
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: bookinfo
    server: https://kubernetes.default.svc
  - namespace: guestbook
    server: https://kubernetes.default.svc
  sourceRepos:
  - '*'
