apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubernetes-ingress-manager-role-binding
subjects:
  - kind: ServiceAccount
    name: kubernetes-ingress-manager-sa
roleRef:
  kind: Role
  name: kubernetes-ingress-manager-role
  apiGroup: rbac.authorization.k8s.io