apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubernetes-event-listener-role-binding
subjects:
  - kind: ServiceAccount
    name: kubernetes-event-listener-sa
roleRef:
  kind: Role
  name: kubernetes-event-listener-role
  apiGroup: rbac.authorization.k8s.io