apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubernetes-workflow-operator-role-binding
subjects:
  - kind: ServiceAccount
    name: kubernetes-workflow-operator-sa
roleRef:
  kind: Role
  name: kubernetes-workflow-operator-role
  apiGroup: rbac.authorization.k8s.io