---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: backstage-tls
spec:
  secretName: backstage-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - backstage.brandt.widdershoven.nl
