---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
  labels:
    app: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      serviceAccountName: backstage
      containers:
        - name: backstage
          image: backstage  # Will be replaced by kustomization
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 7007
              protocol: TCP
          env:
            - name: NODE_ENV
              value: "production"
          # envFrom:
          #   - secretRef:
          #       name: postgres-secrets
          #   - secretRef:
          #       name: backstage-secrets
          volumeMounts:
            - name: app-config
              mountPath: /app/app-config.production.yaml
              subPath: app-config.yaml
              readOnly: true
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
            initialDelaySeconds: 15
            periodSeconds: 5
      volumes:
        - name: app-config
          configMap:
            name: backstage-config
            defaultMode: 420