---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argowf-tls
spec:
  secretName: argowf-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - argowf.brandt.widdershoven.nl
