---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: dev-ghcr-secret
  namespace: backstage-dev
spec:
  encryptedData:
    .dockerconfigjson: AgC0nhqqB0FiWy5/d7uy5dn8fF9/T0B6nlhFPMbXgaB4dfyW8xR1qMtZV1xAiWQKB0tFlkoWIsV7D7CUsx03qAH++aMgCnjX+FFOL3iJTSsHVHb3rVupoo8T552DKpZzwJix/z/140+6u4/kjdgAajHzHiW3cWpdyT2r96k35zeXjeK28z6c/yglF6nbd7Af9hVJ1yFVgjvS+/WmrkI3O3Og780tALg9J0vjTld1tpBF1o05g968+XG1ahQRPEwArZO5KHS+a9QCvuHZ5lMHxbM53umkUuKa+bqjJEHkjczqOEZJk3EuOTRmxziSe103gfNOfFl4+H8OVLoufjXTsOTNtYICv9LqFstyi/d9S/dPPuIXZcf46+9CoTnp3aMUODHl/fiXUscdEQMZCzkmA+3ahu+N3An0sW//OmMFusanMtAHrIk0x1F5BYgDW/pOoh/Z4L6gSguJbuaDoAfGCj8u4jYqAVn/+TuvEix8E1WNllXjW1vKAqTspSKI7ffuWm9NzTBWlwYs7K0Wni5K4gmtjzOBge7phQSbaOVp3A3/5luWOVCfHE/jTJU6btajYxVxlHYnDGcbMh8ShPTv+9jwsZ3ufy8EXn8Zz32UxKqeBpZfA9Qr+nG4SQ9f8RrIZ3OpXqiHFbaYhwUyJzAJ7M5/xt5ENu90ppO4iyEG7L5bJYwG9R9Tc3vi8f//23EcwpqT/gAQqr83MmQ8WvMCkeSEImn22saIfGPSUA8B2Hh4MZhL5eOrm4IIVLDX2bkAkbVwE1TouVFFwskJ+M1U5JnkAlK7cjv+6IfjKbJQiLQpDGhExrTGuvl09s+BAIkU0Xuifmwy7DOa3gM0LV62E6yn2q0ChY0JpwIYhESpJra6B3iPqEi+QV5GK097kTug73odXMEgQbPoEM5ke8aTS/FZExuLgJtCCaGCwrVgbZPrFwj+tSMQF8T+kmyagLkD9w5nVZYNeEXAwikIHG7nzq4oJ+oD9E6zAm2WWftB1jFRVYJiba+gRp/H/dCk08zs4CW1IIcNjJJl0V2WmZK8+IDYJL2SI7xv9APM62UeLYAxsfqk5Fso07X+y19MR4iV6tKi4IMyBAhmKQ==
  template:
    metadata:
      annotations:
        backstage.io/environment: development
        deployment.kubernetes.io/revision: dev
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: backend
        app.kubernetes.io/name: backstage
        app.kubernetes.io/part-of: backstage-dev
        environment: development
      name: dev-ghcr-secret
      namespace: backstage-dev
    type: kubernetes.io/dockerconfigjson
