---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dev-backstage-secret
  namespace: backstage-dev
spec:
  encryptedData:
    GITHUB_CLIENT_ID_DEV: AgAml5xGYIuX8OoNwOwOQjbq60JcWKLWd/weaHAILkaX77tNMCgu51oO2vi8VtrdAP7YtSFW6y+vfeHe+NSSqb23T7v5Nrzp/b/WngyitKU1R9eJWVv7eHfNjHwhjdbWorBgbfJlAJB/dDoHEOlV1qe8IsTaTTw7hxdO7XM02N97QS8OheuSVCWfcfzqluXvjscp6yIGSB1Y9nZ6+RvXVA586rev6LyM/Ryci2R75IBoHQhppv9LlHkVIZZ6f0qEwIEmza87Ys65Yjr2v7QvVe7/zJ2fDlj1P3hra54u8IYrtHXu4zg5+8Ck9U5/W3hwbvoh8Fa/CcmCLxZ+YQDpc4mfzf8nJiapvavbZnwXJBKIgS58ZFzH8WU/X/m+Vytz5ext4JGya4pjbJIflsuQBDIldBZNwRnE+9tC3DXjISWp2OhOAtt9Ro33rYVHFc+j3G2IZQKg/0KtD7rNJ3bywrtHYypfdkM3NkCwHIZGMbi27wxfjtzoPTaMFI465omrjpWAhJX08QRLdvpahmPsXBSf4cWlElKiFJcpnR1jiQ6to44azgioJtVKHFkvgaLnRgGxl2Rs5CH/c/o4/D8sPmVBVhuGMY4JmcWRQH11OstWSmpPQAehiecV5pBGztEgy2pLMXgIgBzPduShuCe+iL7WovDaZzF3Cy9V4HWprw2lQQwQEFueEavzv0KgQb7hdfwHuS1xNjpOPi0cF4/pW7AAkoFlSA==
    GITHUB_CLIENT_SECRET_DEV: AgCbXJoL2oAX4NKBMPP4nIrWu5/f7LbJGUbfkwvVvyBV9FBTH5J1v5zE0CTbUn1i2dn04mYScy+zK2WPVIKYApxjc6YrdTX9aZIA19co+NSlm/dReBw5Fr/H56U5fcw10xNkr3GNbOYGlMbSLTxafJZAEG0GGX/NIMp+72/p1W2tVgnjnHTv0WmGNYmArrUP0CQRDb9G+3P14g011bcv5fVJfRpK1RNQMFxEHOZrSrMN0j2zOycdT22faf8iLeSl2DGb0GF3Su3i34o81wEtbLGEFwkfhoLAfCT4nE+E09zZgM/jPkgFVpBETckEgjOxal9/jfPYM6RD9N3aAP+aJJTEiIdGQ13r5c2qzoiCtLzuHzQsTff6GJB3uxoWzfHqrbfgEu3IBaCL/KIWWkFF4tbH9gaVf3KRu4X5qAXYhJhVB3z2H++4aaXrib02DvHj7XN3jEKoQuzuMu/pnYLjQJ9IB9DEb1HM9KW+LiEX6fvC1aHC+AcB8cHGUYrPvGRTSxeKcQ7lfnRKR5xVqyp1CxtlpcG2kn87kkiyN2ELXOvb8xx2CgAszgDMINI3AdClqQXdF22qqwkpcH5FG2xL1B9vBAbAaxTrr7h4Euc0q4WPu+MUH5zR1X0rAdkvNGH8LbNUhGu8D3xv7MS4wr7VJAGknnw6C9FwBOaokNGZyrhKgD6jNZyW2rF2hmOio6cpJw6Hdy3pkbwwb5b7wdn7CZSsNk/F/ZVI4UvTZWcjExfb5pZSZuoDJvWp
    GITHUB_TOKEN_DEV: AgCtysh1sU8+etcbJAhBSs7zPHttBHoclxUv9jiYId36hE32AF0RTpP18IrX9mWwR6KkbSMoYj+2q1Cu2Uj41CdQTFAogV8pUlw7smNe67ipwbHlJs1MZExwXw6L5E9yLJb2SR6SkIezteMzWBS/Qsm3tp1cAbgeCsvj7UUd1e4NMrzghxO8ZRjSJen2QtzGO5wZGXvKZdfqQAXtYscI41dILleDYHLhgkgRtE32DxAPVOWU9lc8Y6LPeijiK+BiIDoe854Ol+zbF9qKoj7k+QvNIpp8ghUNXgYJT1ome70UC9amCPjFyJpADSoz7WqjSW6FoTUeqTkpFTM9uMRHz5yhqMbT9PVAkV9Oi9NnnCjFF9bhMeaN3h2mQbcavyK+GZ7itkFQE8H4574y7eJGQ9y1ukVxmM7Rl0U0qHQ/M3jwf0UwVjkhZf7lqXbuyQ3Xh4kMp3xgY+o6vOQ34B1esLx5YnvbFoJrOdu/M5azYQFf45yoP5eskQrSlPi4dSi14Cf0t5jFtlwYVRNqc4k5ipwmHGx3h10IZKgwxs8/OjhmY4kev1RmOYuGd11qv/xdvvW4r7JoX5t60aobeexMbtgYAvN80EghkF/Wb9Mq3sqrFQwHLsKNcXNP/Xsbdl3u1iGvUACUofEckC2hS3CFKsr6Fp+7RmTrS7YWH5xwbb3xVgzFgxKNHqPXeiJEG+N+1RIdt9DcRB9b9fJaIGxrDuWjIJvXFHRRH9bPDS7bxXCchDt8oer51vQX6T9pALtEBTEyQk4hPbq3kgJwSWLjlDFPB20G/nXttfnbczBmc84RISQZBBAlm9IPxMkJBMQ=
  template:
    metadata:
      annotations:
        backstage.io/environment: development
        deployment.kubernetes.io/revision: dev
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: backend
        app.kubernetes.io/name: backstage
        app.kubernetes.io/part-of: backstage-dev
        environment: development
      name: dev-backstage-secret
      namespace: backstage-dev
    type: Opaque
