apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubernetes-event-listener-role
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]
