apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubernetes-ingress-manager-role
rules:
  - apiGroups: [""]
    resources: ["ingresses"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
