apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- base/argocd-namespace.yaml
- base/certmanager-certificate.yaml
- base/traefik-ingressroute.yaml
- base/argocd-repositories.yaml
- base/argocd-applications.yaml
- base/argocd-dex-argo-workflow-sso-secret.json
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

patches:
- path: overlays/argocd-cm.yaml
- path: overlays/argocd-cmd-params-cm.yaml
- path: overlays/argocd-dex-server.yaml

images:
- name: quay.io/argoproj/argocd
  newTag: v2.14.6
