---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: ingress-sn
spec:
  template:
    serviceAccountName: kubernetes-workflow-operator-sa
  dependencies:
  - name: service
    eventSourceName: ingress-es
    eventName: ingress
    transform:
      jq: '.operation += if .type == "ADD" then "create" else if .type == "DELETE" then "delete" else "update" end end'
      script: |-
        if event.body.metadata.annotations["deploy-ingress-external"] != "true" then
          event.body.metadata.annotations["traefik.ingress.kubernetes.io/router.middlewares"] = 'default-allow-local-only@kubernetescrd'
        end
        return event

  triggers:
  - template:
      name: ingress
      k8s:
        operation: create
        parameters:
        - src:
            dependencyName: service
            dataKey: operation
          dest: spec.templates.0.steps.0.0.arguments.parameters.0.value
        - src:
            dependencyName: service
            dataKey: body.metadata.annotations.deploy-ingress-class
          dest: spec.templates.0.steps.0.0.arguments.parameters.1.value
        - src:
            dependencyName: service
            dataKey: body.metadata.annotations.deploy-ingress-host
          dest: spec.templates.0.steps.0.0.arguments.parameters.2.value
        - src:
            dependencyName: service
            dataKey: body.metadata.name
          dest: spec.templates.0.steps.0.0.arguments.parameters.3.value
        - src:
            dependencyName: service
            dataKey: body.spec.ports.0.port
            useRawData: true
          dest: spec.templates.0.steps.0.0.arguments.parameters.4.value
        - src:
            dependencyName: service
            dataKey: body.metadata.annotations
          dest: spec.templates.0.steps.0.0.arguments.parameters.5.value
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: create-ingress-for-svc-
            spec:
              serviceAccountName: kubernetes-ingress-manager-sa
              entrypoint: main
              templates:
              - name: main
                steps:
                - - name: apply-ingress-template
                    templateRef:
                      name: manage-ingress
                      template: apply-ingress-template
                    arguments:
                      parameters:
                      - name: operation
                      - name: ingressClassName
                      - name: host
                      - name: serviceName
                      - name: servicePort
                      - name: annotations
