apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argowf

resources:
- base/certmanager-certificate.yaml
- base/traefik-ingressroute.yaml
- https://github.com/argoproj/argo-workflows/releases/download/v3.6.5/install.yaml
